### ISSUE TITLE
Bad Request - Invalid Hostname

### ISSUE THREAD

**Issue by xyz0822** [wintoncode/Winton.Extensions.Configuration.Consul#90] opened 2019-12-04 13:56 UTC
Environment:AspNetCore3.1
Visual Studio Version:16.4.0

On AspNetCore3.0 or AspNetCore3.1 when debugging,I got an "Bad Request - Invalid Hostname" when i put Consul config in program.class.
 ```
Host.CreateDefaultBuilder(args)
            .ConfigureAppConfiguration(config =>
            {
                config.AddConsul("appsettings.json", options =>
                {
                    options.ConsulConfigurationOptions = _ =>
                    {
                        _.Address = new Uri("http://192.168.2.100:8500");
                        _.Datacenter = "dc1";
                    };
                    options.ReloadOnChange = true;
                    options.OnLoadException = ex => { throw ex.Exception; };
                });
            })
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
```

**Comment by Choc13** [comment] 2019-12-04 20:43
Hi @xyz0822,

This sounds like it's just a case of the hostname you've configured for Consul not resolving. Can you confirm that http://192.168.2.100:8500 is the correct address by trying to visit it in the browser?

As a side note, settings `options.OnLoadException = ex => { throw ex.Exception; };` should be the default behaviour. So you should be able to omit that bit of setup.

**Comment by xyz0822** [comment] 2019-12-05 12:28
Yes，that ip was  is correct. and when i comment the the follow line :
config.AddConsul("appsettings.json", options =>
               {
                   options.ConsulConfigurationOptions = _ =>
                   {
                       _.Address = new Uri("http://192.168.2.100:8500");
                       _.Datacenter = "dc1";
                   };
                   options.ReloadOnChange = true;
                   options.OnLoadException = ex => { throw ex.Exception; };
               });
and f5 to debug， the broser returns me:
Bad Request - Invalid Hostname
HTTP Error 400. The request hostname is invalid.

> Hi @xyz0822,
> 
> This sounds like it's just a case of the hostname you've configured for Consul not resolving. Can you confirm that http://192.168.2.100:8500 is the correct address by trying to visit it in the browser?
> 
> As a side note, settings `options.OnLoadException = ex => { throw ex.Exception; };` should be the default behaviour. So you should be able to omit that bit of setup.

**Comment by Choc13** [comment] 2019-12-05 15:59
I've been able to reproduce your issue by starting up the example application in this repo and configuring the Consul address to an invalid hostname, such as `http://foo.bar.baz.net:8500`, but when I put in a valid address it starts up fine. 

The issue here seems to be that your application is unable to find the Consul host you can configured for some reason. I don't think it's an issue with this library.

Are you perhaps running this in Docker or another container environment where the networking configuration might not be configured correctly between the container instances?

**Comment by Choc13** [comment] 2019-12-08 21:51
Closing this as it does not appear to be a problem with this library.

**Closed by Choc13** 2019-12-08 21:51 UTC
Labels: help wanted
