### ISSUE TITLE
How to extract json value from a key?

### ISSUE THREAD

**Issue by TechGeeky** [wintoncode/Winton.Extensions.Configuration.Consul#116] opened 2020-10-11 03:15 UTC
Hi @Choc13 
I have a very simple question where I am stuck so wanted to see if you can help me out.

I have a node (with data) in Consul like below:

```
Node: data/stage/process
Data: 
{
    "key1": true,
    "key2": "value2",
    "key3": {
        "car1": "Ford",
        "car2": "BMW",
        "car3": "Fiat"
    }
}
```
As you can see above, my `key3` is a json object instead of a single string or boolean value.

When I use the below code:

```
    var builder = new ConfigurationBuilder()
        .SetBasePath(env.ContentRootPath)
        .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
        .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
        .AddConsul(
            $"data/stage/process",
            options =>
            {
                options.ConsulConfigurationOptions =
                    cco => { cco.Address = new Uri("some-url"); };
                options.Optional = true;
                options.PollWaitTime = TimeSpan.FromSeconds(5);
                options.ReloadOnChange = true;
                options.OnWatchException = ctx => TimeSpan.FromSeconds(ctx.ConsecutiveFailureCount);
            })
        .AddEnvironmentVariables();
    Configuration = builder.Build();
```

And I try to extract each of those keys value like this:

    string key1 = configuration["key1"];
    string key2 = configuration["key2"];
    string key3 = configuration["key3"];

The value of `key3` is always null but `key1` and `key2` works fine. Any idea why? And how can I get the value of `key3` which is a json object?

**Comment by Choc13** [comment] 2020-10-11 12:14
Hi yes this is expected behaviour. It's actually to do with how the core Microsoft config library works, rather than this specific provider. If you try and access a key that is the parent of other keys, then it's value will be `null` because it doesn't really have a value.

In your particular case you'd need to write `configuration["key3:car1"]` to access a value directly. You can bind all the cars to an object if you want to "deserialise" them all. See the [docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/) for more information on how to extract values from the configuration system. 

I'm going to close this.

**Closed** 2020-10-11 12:14 UTC
